### ISSUE TITLE
Permissions and Responsibilities Structure

### ISSUE THREAD

**Issue by U8NWXD** [vivarium-collective/vivarium-core#142]
GitHub offers the following permission levels for organization repositories ([docs](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations)):

> * Read: Recommended for non-code contributors who want to view or discuss your project
> * Triage: Recommended for contributors who need to proactively manage issues and pull requests without write access
> * Write: Recommended for contributors who actively push to your project
> * Maintain: Recommended for project managers who need to manage the repository without access to sensitive or destructive actions
> * Admin: Recommended for people who need full access to the project, including sensitive and destructive actions like managing security or deleting a repository

I propose the following structure of roles for Vivarium and Vivarium Core (I'm ignoring the other Vivarium repos for now):

* Maintainers: These are the core "owners" of the Vivarium project. They have the `owner` role in the Vivarium Collective organization and the `admin` role in Vivarium Core. They are responsible for enforcing the code of conduct, responding to security vulnerabilities, and adjudicating disputes.
* Collaborators: These are trusted contributors who help develop Vivarium projects. They have the `member` role in the Vivarium Collective organization and the `write` role in Vivarium Core. They are empowered to manage issues, open PRs, and otherwise develop Vivarium Core.
* Public: Anyone can read the Vivarium Core repo, and anyone can contribute by forking the repository and opening a PR. Anyone can also open or comment on a discussion thread or issue.

Remaining Questions:

* Should we require PRs to be approved by certain people? This would probably mean maintainers approve PRs, but collaborators can merge them.
* The Apache CLA is based around the idea of an entity to whom contributors grant a license to use their contributions. Who should this entity be? Maybe the maintainers?

**Comment by eagmon** [comment]
- Current owners of the Vivarium Collective are @U8NWXD @prismofeverything @eagmon, which means we will be the maintainers. I think this is good.
- Right now all `members` of the Vivarium Collective automatically get `write` role in Vivarium Core, and there is no additional access assigned in Vivarium Core. Is this the main path we want to give people a `write` role?

Remaining Questions:
- I think PRs should be approved by maintainers, and that approval should be required before a PR gets merged.
- The Apache CLA -- hmm... We probably can't grant a license to the Vivarium Collective since we are not incorporated. I think the maintainers are the next best thing.
